#!/usr/bin/env ruby

filename = ARGV[0]
user_key = ARGV[1]

if user_key.nil?
  puts "Usage: #{$PROGRAM_NAME} filename username"
  puts "Please provide the a file path you want to import and a user key."
  exit(1)
end

unless File.exists?(filename)
  puts "Unable to read file #{filename}"
  exit(1)
end


puts "Loading environment..."
require_relative('../config/environment')
puts "Importing..."

size = WGBH::MetadataImporter.new(filename, user_key).import

puts "Imported #{size} records."

