#!/usr/bin/env ruby

filename = ARGV[0]

if filename.nil?
  puts "Please provide the a file path you want to import."
  exit(1)
end

unless File.exists?(filename)
  puts "Unable to read file #{filename}"
  exit(1)
end


puts "Loading environment..."
require File.join(File.dirname(__FILE__), '../config/environment.rb')
puts "Importing..."

size = WGBH::MetadataImporter.new(filename).import

puts "Imported #{size} records."

