#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.


(depositor, path) = ARGV[0..1]
unless depositor && path
  puts "USAGE: #{$0} depositor file_path"
  exit 1
end

puts "depositing #{path}"
puts "on behalf of #{depositor}"


require File.expand_path('../../config/environment.rb',  __FILE__)

gf = GenericFile.new(:terms_of_service=>'1')
mime_type = MIME::Types.type_for(path).first.content_type
gf.add_file_datastream(File.open(path), :dsid=>'content', :mimeType=>mime_type)
gf.apply_depositor_metadata(depositor)
gf.save!

puts "Deposited #{path} at #{gf.pid}"

