#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.


(depositor, path) = ARGV[0..1]
unless depositor && path
  puts "USAGE: #{$0} depositor file_path"
  exit 1
end

puts "depositing #{path}"
puts "on behalf of #{depositor}"

require_relative('../config/environment')

gf = GenericFile.new()
gf.apply_depositor_metadata(depositor)
gf.save!
gf.add_file(File.open(path), 'content', File.basename(path))

puts "Deposited #{path} at #{gf.pid}"

